name: Compile Sketch

on:
  push:
    branches:
      - main
    paths:
      - '*.ino'
      - '.github/workflows/compile-sketch.yml'

  pull_request:
    branches:
      - main
    paths:
      - '*.ino'
      - '.github/workflows/compile-sketch.yml'

  workflow_dispatch:

env:
  BOARD_FQBN: esp8266:esp8266:d1_mini:wipe=all

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0
        with:
          version: 1.5.1

      - name: Install ESP8266 Core
        run: |
          arduino-cli config add board_manager.additional_urls "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
          arduino-cli core update-index
          arduino-cli core install "esp8266:esp8266@3.1.2"

      - name: Install Libraries
        run: |
          arduino-cli lib install "AnyRtttl@2.6.0"

      - name: Compile Firmware
        run: |
          mkdir -p build
          arduino-cli compile --fqbn "$BOARD_FQBN" --export-binaries --build-path "./build" .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: firmware-${{ github.sha }}
          path: build/*.bin
          if-no-files-found: error

      - name: GH Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v3.0.2
        with:
          tag_name: firmware
          name: "Latest Firmware"
          body: |
            **FQBN:** ${{ env.BOARD_FQBN }}

            **Compiled on:** ${{ github.event.head_commit.timestamp }}
            **Commit hash:** `${{ github.sha }}`

            ### Included files:
            - `${{ github.event.repository.name }}.ino.bin` - Main firmware
            
            ### How to flash:
            ```bash
            esptool.py --port /dev/ttyUSB0 erase-flash
            esptool.py --port /dev/ttyUSB0 write-flash 0x0 ${{ github.event.repository.name }}.ino.bin
            ```
          files: build/*.bin
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
